
server:
  port: 8384
spring:
  application:
    name: CAB_USER_SERVICE

  kafka:
    consumer:
      group-id: user-group
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest